"""Pydantic models for the AI radiology-report endpoint.

Every response carries a prominent RESEARCH-ONLY disclaimer: the underlying
MedRAX models are unvalidated and this software is NOT a medical device.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

RESEARCH_ONLY_DISCLAIMER = (
    "RESEARCH ONLY -- NOT FOR CLINICAL USE. This report was generated by the "
    "vendored MedRAX research agent (arXiv:2502.02673) and an LLM narrative "
    "step. It is unvalidated, may be incorrect, and must NOT be used for "
    "diagnosis or treatment. PulmoCare is not a medical device. A qualified "
    "clinician must review and edit any output before any use."
)


class RadiologyReportRequest(BaseModel):
    """Request for a structured chest X-ray report."""

    image_path: str = Field(
        ...,
        description="Server-side path to a chest X-ray image (JPG or PNG).",
        examples=["/data/cxr/normal1.jpg"],
    )
    question: str | None = Field(
        default=None,
        description="Optional clinical question for the VQA tool (xray_vqa).",
        examples=["Is there evidence of pleural effusion?"],
    )
    include_narrative: bool = Field(
        default=True,
        description=(
            "If true, add an LLM-generated plain-language narrative "
            "(claude-haiku-4-5) summarizing the structured findings."
        ),
    )


class RadiologyReport(BaseModel):
    """Structured chest X-ray report with a mandatory research-only banner."""

    disclaimer: str = Field(
        default=RESEARCH_ONLY_DISCLAIMER,
        description="Mandatory research-only / not-a-medical-device banner.",
    )
    research_only: bool = Field(
        default=True,
        description="Always true; pinned so clients cannot mistake this for clinical output.",
    )
    image_path: str
    findings: str | None = Field(default=None, description="Detailed observations (MedRAX findings model).")
    impression: str | None = Field(default=None, description="Concise interpretation (MedRAX impression model).")
    vqa_question: str | None = None
    vqa_answer: str | None = Field(default=None, description="Answer from the MedRAX xray_vqa tool, if asked.")
    narrative: str | None = Field(
        default=None,
        description="Optional plain-language narrative (claude-haiku-4-5).",
    )
    model_status: str = Field(
        default="completed",
        description="completed | degraded | failed -- whether MedRAX weights were available.",
    )
    detail: str | None = Field(default=None, description="Human-readable status detail (e.g. why degraded).")
