// English translations
const Map<String, String> englishTranslations = {
  // General
  'app_name': 'Pulmocare',
  'ok': 'OK',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'loading': 'Loading...',
  'save': 'Save',
  'search': 'Search',
  'delete': 'Delete',
  'edit': 'Edit',
  'welcome': 'Welcome',

  // Auth
  'login': 'Login',
  'signup': 'Sign Up',
  'logout': 'Logout',
  'logout_confirmation': 'Are you sure you want to logout?',
  'email': 'Email',
  'password': 'Password',
  'forgot_password': 'Forgot Password?',
  'continue_with': 'Or continue with',
  'dont_have_account': 'Don\'t have an account?',
  'already_have_account': 'Already have an account?',
  'create_account': 'Create Account',

  // Dashboard
  'hello_doctor': 'Hello, Dr.',
  'todays_agenda': 'Today\'s Agenda',
  'appointments_today': 'Appointments Today',
  'patients_to_see': 'Patients to See',
  'recent_patients': 'Recent Patients',
  'view_all': 'View All',
  'statistics': 'Statistics',
  'this_week': 'This Week',
  'this_month': 'This Month',
  'total_appointments': 'Total Appointments',
  'total_patients': 'Total Patients',
  'upcoming_appointments': 'Upcoming Appointments',
  'no_appointments': 'No upcoming appointments',
  'see_schedule': 'See Full Schedule',

  // Patients
  'patient_details': 'Patient Details',
  'personal_info': 'Personal Information',
  'medical_history': 'Medical History',
  'age': 'Age',
  'gender': 'Gender',
  'blood_type': 'Blood Type',
  'contact': 'Contact',
  'address': 'Address',
  'phone': 'Phone',
  'allergies': 'Allergies',
  'medications': 'Current Medications',
  'visit_history': 'Visit History',
  'last_visit': 'Last Visit',
  'notes': 'Notes',
  'add_note': 'Add Note',
  'prescriptions': 'Prescriptions',
  'tests': 'Lab Tests',
  'new_patient': 'New Patient',

  // Appointments
  'schedule': 'Schedule',
  'calendar': 'Calendar',
  'upcoming': 'Upcoming',
  'past': 'Past',
  'cancelled': 'Cancelled',
  'appointment_details': 'Appointment Details',
  'appointment_with': 'Appointment with',
  'date': 'Date',
  'time': 'Time',
  'duration': 'Duration',
  'reason': 'Reason for Visit',
  'reschedule': 'Reschedule',
  'cancel_appointment': 'Cancel Appointment',
  'book_appointment': 'Book Appointment',
  'select_date': 'Select Date',
  'select_time': 'Select Time',
  'select_patient': 'Select Patient',
  'appointment_type': 'Appointment Type',
  'in_person': 'In Person',
  'virtual': 'Virtual',

  // Messages/Chat
  'messages': 'Messages',
  'no_messages': 'No messages yet',
  'new_message': 'New Message',
  'send_message': 'Send Message',
  'search_contacts': 'Search Contacts',
  'type_message': 'Type a message...',
  'send': 'Send',
  'attach': 'Attach',

  // Navigation & Drawer
  'dashboard': 'Dashboard',
  'patients': 'Patients',
  'appointments': 'Appointments',
  'settings': 'Settings',
  'profile': 'Profile',
  'dark_mode': 'Dark Mode',
  'language': 'Language',
  'privacy': 'Privacy',
  'help_support': 'Help & Support',
  'about': 'About',
  'select_language': 'Select Language',
  'english': 'English',
  'french': 'French',
  'arabic': 'Arabic',

  // Settings
  'notifications': 'Notifications',
  'account': 'Account',
  'security': 'Security',
  'appearance': 'Appearance',
  'language_region': 'Language & Region',
  'help': 'Help',
  'about_app': 'About App',
  'password_security': 'Password & Security',
  'change_password': 'Change Password',
  'enable_biometrics': 'Enable Biometrics',
  'two_factor_auth': 'Two-Factor Authentication',
  'update_profile': 'Update Profile',

  // Privacy & Terms
  'privacy_policy': 'Privacy Policy',
  'terms_of_service': 'Terms of Service',
  'last_updated': 'Last Updated: May 15, 2025',

  // Help & Support
  'contact_support': 'Contact Support',
  'user_guide': 'User Guide',
  'version': 'Version',
  'submit_ticket': 'Submit a Support Ticket',
  'live_chat': 'Live Chat',

  // About
  'about_pulmocare': 'About Pulmocare',
  'pulmocare_description':
      'Pulmocare is a healthcare platform designed to connect doctors with patients seamlessly. Our mission is to improve healthcare access and quality through technology.',
  'all_rights_reserved': '© 2025 Pulmocare. All rights reserved.',

  // Error messages
  'error_occurred': 'An error occurred',
  'try_again': 'Please try again',
  'no_internet': 'No internet connection',
  'not_found': 'Not found',
  'session_expired': 'Session expired, please login again',

  // New additions for all screens
  'scan_visit_card': 'Scan Visit Card',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'name_required': 'Name is required',
  'name_min_length': 'Name must be at least 2 characters',
  'email_required': 'Email is required',
  'email_invalid': 'Please enter a valid email',
  'password_required': 'Password is required',
  'password_min_length': 'Password must be at least 8 characters',
  'specialty_required': 'Specialty is required',
  'phone_required': 'Phone number is required',
  'address_required': 'Address is required',
  'full_name': 'Full Name',
  'fill_details_below': 'Please fill in the details below',
  'welcome_back': 'Welcome Back',
  'sign_in_as': 'Sign in as',
  'appointments_coming_soon': 'Appointments Coming Soon',
  'settings_coming_soon': 'Settings Coming Soon',
  'search_location': 'Search location',
  'confirm_location': 'Confirm Location',

  // Profile View
  'email_address': 'Email Address',
  'phone_number': 'Phone Number',
  'office_address': 'Office Address',
  'view_signature': 'View Signature',
  'add_signature': 'Add Signature',
  'edit_profile': 'Edit\nProfile',
  'current_password': 'Current Password',
  'new_password': 'New Password',
  'confirm_new_password': 'Confirm New Password',
  'current_password_required': 'Please enter your current password',
  'new_password_required': 'Please enter a new password',
  'confirm_password_required': 'Please confirm your new password',
  'new_password_different':
      'New password must be different from current password',
  'passwords_do_not_match': 'Passwords do not match',
  'password_updated': 'Password updated successfully',
  'password_change_failed': 'Failed to change password',
  'select_profile_image': 'Select Profile Image',
  'save_changes': 'Save Changes',
  'your_signature': 'Your Signature',
  'change': 'Change',
  'close': 'Close',

  // News View
  'medical_news': 'Medical News',
  'select_specialty': 'Select Specialty',
  'loading_news': 'Loading news...',
  'no_news': 'No news available',
  'read_more': 'Read More',
  'published_on': 'Published on',
  'news_source': 'Source:',

  // Patient Selection
  'search_patient': 'Search Patient',
  'no_patients_found': 'No patients found',
  'all_patients': 'All Patients',

  // Entry View
  'welcome_to_pulmocare': 'Welcome to Pulmocare',
  'healthcare_platform': 'Healthcare platform for medical professionals',
  'get_started': 'Get Started',
  'doctor_login': 'Doctor Login',
  'patient_login': 'Patient Login',
  'admin_login': 'Admin Login',
  'continue_as_guest': 'Continue as Guest',
  'healthcare_made_simple': 'Healthcare Made Simple',
  'connecting_patients_doctors': 'Connecting patients and doctors effortlessly',
  'manage_your_health': 'Manage your health with ease',
  'slide_to_continue': 'Slide to continue',
  'control_your_practice': 'Control Your Practice',
  'manage_appointments':
      'Manage appointments, prescriptions and patient records',
  'ai_powered_tools': 'AI-powered tools for better diagnosis',
  'secure_communication': 'Secure Communication',
  'end_to_end_encryption': 'End-to-end encrypted messaging',
  'share_medical_records': 'Securely share medical records and test results',
  'privacy_compliance': 'HIPAA compliant privacy protection',

  // Forgot Password View
  'forgot_password_title': 'Forgot Password',
  'forgot_password_subtitle':
      'Enter your email to receive a password reset code',
  'reset_password': 'Reset Password',
  'enter_email_address': 'Enter your email address',
  'send_code': 'Send Code',
  'enter_verification_code': 'Enter Verification Code',
  'code_sent': 'A verification code has been sent to your email',
  'didnt_receive_code': 'Didn\'t receive the code?',
  'resend_code': 'Resend Code',
  'verify_code': 'Verify Code',
  'enter_new_password': 'Enter New Password',
  'confirm_password': 'Confirm Password',
  'password_requirements':
      'Password must be at least 8 characters and include numbers and symbols',
  'passwords_must_match': 'Passwords must match',
  'password_reset_success': 'Password reset successful!',
  'back_to_login': 'Back to Login',

  // Drawer Content
  'navigation': 'Navigation',
  'home': 'Home',
  'chat': 'Chat',
  'medical_records': 'Medical Records',
  'lab_results': 'Lab Results',
  'billing': 'Billing',
  'sign_up': 'Sign Up',
  'visit_website': 'Visit Website',
  'contact_us': 'Contact Us',
  'faq': 'FAQ',
  'terms_conditions': 'Terms & Conditions',
  'rate_app': 'Rate App',
  'share_app': 'Share App',

  // Child Health Risk Prediction
  'Child Health Risk Assessment': 'Child Health Risk Assessment',
  'Child Health Risk Predictor': 'Child Health Risk Predictor',
  'About this tool': 'About this tool',
  'This tool helps estimate potential health risks for children based on parental conditions and lifestyle factors. The results are for informational purposes only and should not replace professional medical advice.':
      'This tool helps estimate potential health risks for children based on parental conditions and lifestyle factors. The results are for informational purposes only and should not replace professional medical advice.',
  'Child Details': 'Child Details',
  'Height (cm)': 'Height (cm)',
  'Weight (kg)': 'Weight (kg)',
  'Optional': 'Optional',
  'Parental Health Conditions': 'Parental Health Conditions',
  'Select all conditions that apply to biological parents':
      'Select all conditions that apply to biological parents',
  'Lifestyle Factors': 'Lifestyle Factors',
  'Select all that apply to the child\'s current lifestyle':
      'Select all that apply to the child\'s current lifestyle',
  'Calculate Health Risks': 'Calculate Health Risks',
  'Overall Health Risk Score': 'Overall Health Risk Score',
  'Risk Categories': 'Risk Categories',
  'Recommendations': 'Recommendations',
  'Low Risk': 'Low Risk',
  'Moderate Risk': 'Moderate Risk',
  'High Risk': 'High Risk',
  'Start New Assessment': 'Start New Assessment',
  'Start Assessment': 'Start Assessment',
  'Later': 'Later',
  'Assess hereditary risk factors': 'Assess hereditary risk factors',
  'Evaluate lifestyle impact': 'Evaluate lifestyle impact',
  'Get personalized recommendations': 'Get personalized recommendations',
  'Track progress over time': 'Track progress over time',
  'Potential Associated Conditions:': 'Potential Associated Conditions:',
  'Risk': 'Risk',
  'Disclaimer: This assessment is for informational purposes only and does not constitute medical advice. Always consult with healthcare professionals for proper medical guidance.':
      'Disclaimer: This assessment is for informational purposes only and does not constitute medical advice. Always consult with healthcare professionals for proper medical guidance.',
};

// French translations
const Map<String, String> frenchTranslations = {
  // General
  'app_name': 'Pulmocare',
  'ok': 'OK',
  'cancel': 'Annuler',
  'confirm': 'Confirmer',
  'loading': 'Chargement...',
  'save': 'Enregistrer',
  'search': 'Rechercher',
  'delete': 'Supprimer',
  'edit': 'Modifier',
  'welcome': 'Bienvenue',

  // Auth
  'login': 'Connexion',
  'signup': 'S\'inscrire',
  'logout': 'Déconnexion',
  'logout_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter?',
  'email': 'E-mail',
  'password': 'Mot de passe',
  'forgot_password': 'Mot de passe oublié?',
  'continue_with': 'Ou continuer avec',
  'dont_have_account': 'Vous n\'avez pas de compte?',
  'already_have_account': 'Vous avez déjà un compte?',
  'create_account': 'Créer un compte',

  // Dashboard
  'hello_doctor': 'Bonjour, Dr.',
  'todays_agenda': 'Agenda d\'aujourd\'hui',
  'appointments_today': 'Rendez-vous aujourd\'hui',
  'patients_to_see': 'Patients à voir',
  'recent_patients': 'Patients récents',
  'view_all': 'Voir tout',
  'statistics': 'Statistiques',
  'this_week': 'Cette semaine',
  'this_month': 'Ce mois',
  'total_appointments': 'Total des rendez-vous',
  'total_patients': 'Total des patients',
  'upcoming_appointments': 'Rendez-vous à venir',
  'no_appointments': 'Aucun rendez-vous à venir',
  'see_schedule': 'Voir l\'agenda complet',

  // Patients
  'patient_details': 'Détails du patient',
  'personal_info': 'Informations personnelles',
  'medical_history': 'Antécédents médicaux',
  'age': 'Âge',
  'gender': 'Genre',
  'blood_type': 'Groupe sanguin',
  'contact': 'Contact',
  'address': 'Adresse',
  'phone': 'Téléphone',
  'allergies': 'Allergies',
  'medications': 'Médicaments actuels',
  'visit_history': 'Historique des visites',
  'last_visit': 'Dernière visite',
  'notes': 'Notes',
  'add_note': 'Ajouter une note',
  'prescriptions': 'Ordonnances',
  'tests': 'Tests de laboratoire',
  'new_patient': 'Nouveau patient',

  // Appointments
  'schedule': 'Programme',
  'calendar': 'Calendrier',
  'upcoming': 'À venir',
  'past': 'Passé',
  'cancelled': 'Annulé',
  'appointment_details': 'Détails du rendez-vous',
  'appointment_with': 'Rendez-vous avec',
  'date': 'Date',
  'time': 'Heure',
  'duration': 'Durée',
  'reason': 'Motif de la visite',
  'reschedule': 'Reprogrammer',
  'cancel_appointment': 'Annuler le rendez-vous',
  'book_appointment': 'Prendre rendez-vous',
  'select_date': 'Sélectionner une date',
  'select_time': 'Sélectionner une heure',
  'select_patient': 'Sélectionner un patient',
  'appointment_type': 'Type de rendez-vous',
  'in_person': 'En personne',
  'virtual': 'Virtuel',

  // Messages/Chat
  'messages': 'Messages',
  'no_messages': 'Pas encore de messages',
  'new_message': 'Nouveau message',
  'send_message': 'Envoyer un message',
  'search_contacts': 'Rechercher des contacts',
  'type_message': 'Tapez un message...',
  'send': 'Envoyer',
  'attach': 'Joindre',

  // Navigation & Drawer
  'dashboard': 'Tableau de bord',
  'patients': 'Patients',
  'appointments': 'Rendez-vous',
  'settings': 'Paramètres',
  'profile': 'Profil',
  'dark_mode': 'Mode sombre',
  'language': 'Langue',
  'privacy': 'Confidentialité',
  'help_support': 'Aide et support',
  'about': 'À propos',
  'select_language': 'Sélectionner la langue',
  'english': 'Anglais',
  'french': 'Français',
  'arabic': 'Arabe',

  // Settings
  'notifications': 'Notifications',
  'account': 'Compte',
  'security': 'Sécurité',
  'appearance': 'Apparence',
  'language_region': 'Langue et région',
  'help': 'Aide',
  'about_app': 'À propos de l\'application',
  'password_security': 'Mot de passe et sécurité',
  'change_password': 'Changer le mot de passe',
  'enable_biometrics': 'Activer la biométrie',
  'two_factor_auth': 'Authentification à deux facteurs',
  'update_profile': 'Mettre à jour le profil',

  // Privacy & Terms
  'privacy_policy': 'Politique de confidentialité',
  'terms_of_service': 'Conditions d\'utilisation',
  'last_updated': 'Dernière mise à jour: 15 mai 2025',

  // Help & Support
  'contact_support': 'Contacter le support',
  'user_guide': 'Guide d\'utilisation',
  'version': 'Version',
  'submit_ticket': 'Soumettre un ticket de support',
  'live_chat': 'Chat en direct',

  // About
  'about_pulmocare': 'À propos de Pulmocare',
  'pulmocare_description':
      'Pulmocare est une plateforme de santé conçue pour connecter les médecins et les patients de manière transparente. Notre mission est d\'améliorer l\'accès et la qualité des soins de santé grâce à la technologie.',
  'all_rights_reserved': '© 2025 Pulmocare. Tous droits réservés.',

  // Error messages
  'error_occurred': 'Une erreur s\'est produite',
  'try_again': 'Veuillez réessayer',
  'no_internet': 'Pas de connexion internet',
  'not_found': 'Non trouvé',
  'session_expired': 'Session expirée, veuillez vous reconnecter',

  // New additions for all screens
  'scan_visit_card': 'Scanner la Carte de Visite',
  'camera': 'Caméra',
  'gallery': 'Galerie',
  'name_required': 'Le nom est requis',
  'name_min_length': 'Le nom doit comporter au moins 2 caractères',
  'email_required': 'L\'email est requis',
  'email_invalid': 'Veuillez entrer un email valide',
  'password_required': 'Le mot de passe est requis',
  'password_min_length': 'Le mot de passe doit comporter au moins 8 caractères',
  'specialty_required': 'La spécialité est requise',
  'phone_required': 'Le numéro de téléphone est requis',
  'address_required': 'L\'adresse est requise',
  'full_name': 'Nom Complet',
  'fill_details_below': 'Veuillez remplir les détails ci-dessous',
  'welcome_back': 'Bienvenue à Nouveau',
  'sign_in_as': 'Connectez-vous en tant que',
  'appointments_coming_soon': 'Rendez-vous à Venir Bientôt',
  'settings_coming_soon': 'Paramètres à Venir Bientôt',
  'search_location': 'Rechercher un lieu',
  'confirm_location': 'Confirmer l\'Emplacement',

  // Profile View
  'email_address': 'Adresse Email',
  'phone_number': 'Numéro de Téléphone',
  'office_address': 'Adresse du Cabinet',
  'view_signature': 'Voir la Signature',
  'add_signature': 'Ajouter une Signature',
  'edit_profile': 'Modifier\nProfil',
  'current_password': 'Mot de Passe Actuel',
  'new_password': 'Nouveau Mot de Passe',
  'confirm_new_password': 'Confirmer le Nouveau Mot de Passe',
  'current_password_required': 'Veuillez entrer votre mot de passe actuel',
  'new_password_required': 'Veuillez entrer un nouveau mot de passe',
  'confirm_password_required': 'Veuillez confirmer votre nouveau mot de passe',
  'new_password_different':
      'Le nouveau mot de passe doit être différent du mot de passe actuel',
  'passwords_do_not_match': 'Les mots de passe ne correspondent pas',
  'password_updated': 'Mot de passe mis à jour avec succès',
  'password_change_failed': 'Échec du changement de mot de passe',
  'select_profile_image': 'Sélectionner une Image de Profil',
  'save_changes': 'Sauvegarder les Modifications',
  'your_signature': 'Votre Signature',
  'change': 'Modifier',
  'close': 'Fermer',

  // News View
  'medical_news': 'Actualités Médicales',
  'select_specialty': 'Sélectionner une Spécialité',
  'loading_news': 'Chargement des actualités...',
  'no_news': 'Aucune actualité disponible',
  'read_more': 'Lire la Suite',
  'published_on': 'Publié le',
  'news_source': 'Source:',

  // Patient Selection
  'search_patient': 'Rechercher un Patient',
  'no_patients_found': 'Aucun patient trouvé',
  'all_patients': 'Tous les Patients',

  // Entry View
  'welcome_to_pulmocare': 'Bienvenue sur Pulmocare',
  'healthcare_platform': 'Plateforme de santé pour les professionnels médicaux',
  'get_started': 'Commencer',
  'doctor_login': 'Connexion Médecin',
  'patient_login': 'Connexion Patient',
  'admin_login': 'Connexion Admin',
  'continue_as_guest': 'Continuer en tant qu\'invité',
  'healthcare_made_simple': 'Soins de santé simplifiés',
  'connecting_patients_doctors':
      'Connexion sans effort entre patients et médecins',
  'manage_your_health': 'Gérez votre santé facilement',
  'slide_to_continue': 'Glissez pour continuer',
  'control_your_practice': 'Contrôlez votre pratique',
  'manage_appointments':
      'Gérez les rendez-vous, les ordonnances et les dossiers des patients',
  'ai_powered_tools': 'Outils basés sur l\'IA pour un meilleur diagnostic',
  'secure_communication': 'Communication sécurisée',
  'end_to_end_encryption': 'Messagerie chiffrée de bout en bout',
  'share_medical_records':
      'Partagez en toute sécurité les dossiers médicaux et les résultats de tests',
  'privacy_compliance': 'Protection de la vie privée conforme à HIPAA',

  // Forgot Password View
  'forgot_password_title': 'Mot de passe oublié',
  'forgot_password_subtitle':
      'Entrez votre email pour recevoir un code de réinitialisation',
  'reset_password': 'Réinitialiser le mot de passe',
  'enter_email_address': 'Entrez votre adresse e-mail',
  'send_code': 'Envoyer le code',
  'enter_verification_code': 'Entrez le code de vérification',
  'code_sent': 'Un code de vérification a été envoyé à votre email',
  'didnt_receive_code': 'Vous n\'avez pas reçu le code ?',
  'resend_code': 'Renvoyer le code',
  'verify_code': 'Vérifier le code',
  'enter_new_password': 'Entrez un nouveau mot de passe',
  'confirm_password': 'Confirmez le mot de passe',
  'password_requirements':
      'Le mot de passe doit contenir au moins 8 caractères et inclure des chiffres et des symboles',
  'passwords_must_match': 'Les mots de passe doivent correspondre',
  'password_reset_success': 'Réinitialisation du mot de passe réussie !',
  'back_to_login': 'Retour à la connexion',

  // Drawer Content
  'navigation': 'Navigation',
  'home': 'Accueil',
  'chat': 'Discussion',
  'medical_records': 'Dossiers Médicaux',
  'lab_results': 'Résultats de Laboratoire',
  'billing': 'Facturation',
  'sign_up': 'S\'inscrire',
  'visit_website': 'Visiter le Site Web',
  'contact_us': 'Contactez-nous',
  'faq': 'FAQ',
  'terms_conditions': 'Termes et Conditions',
  'rate_app': 'Évaluer l\'application',
  'share_app': 'Partager l\'application',
};

// Arabic translations
const Map<String, String> arabicTranslations = {
  // General
  'app_name': 'بولموكير',
  'ok': 'موافق',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'loading': 'جاري التحميل...',
  'save': 'حفظ',
  'search': 'بحث',
  'delete': 'حذف',
  'edit': 'تعديل',
  'welcome': 'مرحباً',

  // Auth
  'login': 'تسجيل الدخول',
  'signup': 'تسجيل',
  'logout': 'تسجيل الخروج',
  'logout_confirmation': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'forgot_password': 'نسيت كلمة المرور؟',
  'continue_with': 'أو استمر باستخدام',
  'dont_have_account': 'ليس لديك حساب؟',
  'already_have_account': 'هل لديك حساب بالفعل؟',
  'create_account': 'إنشاء حساب',

  // Dashboard
  'hello_doctor': 'مرحباً د.',
  'todays_agenda': 'جدول اليوم',
  'appointments_today': 'مواعيد اليوم',
  'patients_to_see': 'المرضى للمقابلة',
  'recent_patients': 'المرضى الأخيرين',
  'view_all': 'عرض الكل',
  'statistics': 'الإحصائيات',
  'this_week': 'هذا الأسبوع',
  'this_month': 'هذا الشهر',
  'total_appointments': 'إجمالي المواعيد',
  'total_patients': 'إجمالي المرضى',
  'upcoming_appointments': 'المواعيد القادمة',
  'no_appointments': 'لا توجد مواعيد قادمة',
  'see_schedule': 'عرض الجدول كاملاً',

  // Patients
  'patient_details': 'تفاصيل المريض',
  'personal_info': 'المعلومات الشخصية',
  'medical_history': 'التاريخ الطبي',
  'age': 'العمر',
  'gender': 'الجنس',
  'blood_type': 'فصيلة الدم',
  'contact': 'التواصل',
  'address': 'العنوان',
  'phone': 'الهاتف',
  'allergies': 'الحساسية',
  'medications': 'الأدوية الحالية',
  'visit_history': 'سجل الزيارات',
  'last_visit': 'آخر زيارة',
  'notes': 'ملاحظات',
  'add_note': 'إضافة ملاحظة',
  'prescriptions': 'الوصفات الطبية',
  'tests': 'الفحوصات المخبرية',
  'new_patient': 'مريض جديد',

  // Appointments
  'schedule': 'الجدول',
  'calendar': 'التقويم',
  'upcoming': 'القادمة',
  'past': 'السابقة',
  'cancelled': 'الملغاة',
  'appointment_details': 'تفاصيل الموعد',
  'appointment_with': 'موعد مع',
  'date': 'التاريخ',
  'time': 'الوقت',
  'duration': 'المدة',
  'reason': 'سبب الزيارة',
  'reschedule': 'إعادة جدولة',
  'cancel_appointment': 'إلغاء الموعد',
  'book_appointment': 'حجز موعد',
  'select_date': 'اختر التاريخ',
  'select_time': 'اختر الوقت',
  'select_patient': 'اختر المريض',
  'appointment_type': 'نوع الموعد',
  'in_person': 'شخصي',
  'virtual': 'افتراضي',

  // Messages/Chat
  'messages': 'الرسائل',
  'no_messages': 'لا توجد رسائل بعد',
  'new_message': 'رسالة جديدة',
  'send_message': 'إرسال رسالة',
  'search_contacts': 'البحث عن جهات الاتصال',
  'type_message': 'اكتب رسالة...',
  'send': 'إرسال',
  'attach': 'إرفاق',

  // Navigation & Drawer
  'dashboard': 'لوحة التحكم',
  'patients': 'المرضى',
  'appointments': 'المواعيد',
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'dark_mode': 'الوضع الداكن',
  'language': 'اللغة',
  'privacy': 'الخصوصية',
  'help_support': 'المساعدة والدعم',
  'about': 'حول',
  'select_language': 'اختر اللغة',
  'english': 'الإنجليزية',
  'french': 'الفرنسية',
  'arabic': 'العربية',

  // Settings
  'notifications': 'الإشعارات',
  'account': 'الحساب',
  'security': 'الأمان',
  'appearance': 'المظهر',
  'language_region': 'اللغة والمنطقة',
  'help': 'المساعدة',
  'about_app': 'عن التطبيق',
  'password_security': 'كلمة المرور والأمان',
  'change_password': 'تغيير\nكلمة المرور',
  'enable_biometrics': 'تمكين المقاييس الحيوية',
  'two_factor_auth': 'المصادقة الثنائية',
  'update_profile': 'تحديث الملف الشخصي',

  // Privacy & Terms
  'privacy_policy': 'سياسة الخصوصية',
  'terms_of_service': 'شروط الخدمة',
  'last_updated': 'آخر تحديث: 15 مايو 2025',

  // Help & Support
  'contact_support': 'الاتصال بالدعم',
  'user_guide': 'دليل المستخدم',
  'version': 'الإصدار',
  'submit_ticket': 'تقديم تذكرة دعم',
  'live_chat': 'الدردشة المباشرة',

  // About
  'about_pulmocare': 'حول بولموكير',
  'pulmocare_description':
      'بولموكير هي منصة رعاية صحية مصممة لربط الأطباء بالمرضى بسلاسة. مهمتنا هي تحسين الوصول إلى الرعاية الصحية وجودتها من خلال التكنولوجيا.',
  'all_rights_reserved': '© 2025 بولموكير. جميع الحقوق محفوظة.',

  // Error messages
  'error_occurred': 'حدث خطأ',
  'try_again': 'يرجى المحاولة مرة أخرى',
  'no_internet': 'لا يوجد اتصال بالإنترنت',
  'not_found': 'غير موجود',
  'session_expired': 'انتهت الجلسة، يرجى تسجيل الدخول مرة أخرى',

  // New additions for all screens
  'scan_visit_card': 'مسح بطاقة الزيارة',
  'camera': 'الكاميرا',
  'gallery': 'المعرض',
  'name_required': 'الاسم مطلوب',
  'name_min_length': 'يجب أن يكون الاسم على الأقل حرفين',
  'email_required': 'البريد الإلكتروني مطلوب',
  'email_invalid': 'الرجاء إدخال بريد إلكتروني صالح',
  'password_required': 'كلمة المرور مطلوبة',
  'password_min_length': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
  'specialty_required': 'التخصص مطلوب',
  'phone_required': 'رقم الهاتف مطلوب',
  'address_required': 'العنوان مطلوب',
  'full_name': 'الاسم الكامل',
  'fill_details_below': 'يرجى ملء التفاصيل أدناه',
  'welcome_back': 'مرحبًا بعودتك',
  'sign_in_as': 'تسجيل الدخول كـ',
  'appointments_coming_soon': 'المواعيد قادمة قريبًا',
  'settings_coming_soon': 'الإعدادات قادمة قريبًا',
  'search_location': 'البحث عن موقع',
  'confirm_location': 'تأكيد الموقع',

  // Profile View
  'email_address': 'عنوان البريد الإلكتروني',
  'phone_number': 'رقم الهاتف',
  'office_address': 'عنوان العيادة',
  'view_signature': 'عرض التوقيع',
  'add_signature': 'إضافة توقيع',
  'edit_profile': 'تعديل\nالملف الشخصي',
  'current_password': 'كلمة المرور الحالية',
  'new_password': 'كلمة المرور الجديدة',
  'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
  'current_password_required': 'الرجاء إدخال كلمة المرور الحالية',
  'new_password_required': 'الرجاء إدخال كلمة مرور جديدة',
  'confirm_password_required': 'الرجاء تأكيد كلمة المرور الجديدة',
  'new_password_different':
      'يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمة المرور الحالية',
  'passwords_do_not_match': 'كلمات المرور غير متطابقة',
  'password_updated': 'تم تحديث كلمة المرور بنجاح',
  'password_change_failed': 'فشل تغيير كلمة المرور',
  'select_profile_image': 'اختر صورة الملف الشخصي',
  'save_changes': 'حفظ التغييرات',
  'your_signature': 'توقيعك',
  'change': 'تغيير',
  'close': 'إغلاق',

  // News View
  'medical_news': 'الأخبار الطبية',
  'select_specialty': 'اختر التخصص',
  'loading_news': 'جاري تحميل الأخبار...',
  'no_news': 'لا توجد أخبار متاحة',
  'read_more': 'قراءة المزيد',
  'published_on': 'نشر في',
  'news_source': 'المصدر:',

  // Patient Selection
  'search_patient': 'البحث عن مريض',
  'no_patients_found': 'لم يتم العثور على مرضى',
  'all_patients': 'جميع المرضى',

  // Entry View
  'welcome_to_pulmocare': 'مرحباً بك في بولموكير',
  'healthcare_platform': 'منصة رعاية صحية للمتخصصين الطبيين',
  'get_started': 'البدء',
  'doctor_login': 'تسجيل دخول الطبيب',
  'patient_login': 'تسجيل دخول المريض',
  'admin_login': 'تسجيل دخول المدير',
  'continue_as_guest': 'المتابعة كضيف',
  'healthcare_made_simple': 'الرعاية الصحية ببساطة',
  'connecting_patients_doctors': 'ربط المرضى والأطباء بسهولة',
  'manage_your_health': 'إدارة صحتك بسهولة',
  'slide_to_continue': 'مرر للاستمرار',
  'control_your_practice': 'تحكم في ممارستك',
  'manage_appointments': 'إدارة المواعيد والوصفات الطبية وسجلات المرضى',
  'ai_powered_tools': 'أدوات مدعومة بالذكاء الاصطناعي لتشخيص أفضل',
  'secure_communication': 'اتصال آمن',
  'end_to_end_encryption': 'تشفير الرسائل من طرف إلى طرف',
  'share_medical_records': 'مشاركة السجلات الطبية ونتائج الاختبارات بشكل آمن',
  'privacy_compliance': 'حماية الخصوصية المتوافقة مع HIPAA',

  // Forgot Password View
  'forgot_password_title': 'نسيت كلمة المرور',
  'forgot_password_subtitle':
      'أدخل بريدك الإلكتروني لتلقي رمز إعادة ضبط كلمة المرور',
  'reset_password': 'إعادة ضبط كلمة المرور',
  'enter_email_address': 'أدخل عنوان بريدك الإلكتروني',
  'send_code': 'إرسال الرمز',
  'enter_verification_code': 'أدخل رمز التحقق',
  'code_sent': 'تم إرسال رمز التحقق إلى بريدك الإلكتروني',
  'didnt_receive_code': 'لم تستلم الرمز؟',
  'resend_code': 'إعادة إرسال الرمز',
  'verify_code': 'التحقق من الرمز',
  'enter_new_password': 'أدخل كلمة المرور الجديدة',
  'confirm_password': 'تأكيد كلمة المرور',
  'password_requirements':
      'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل وتتضمن أرقامًا ورموزًا',
  'passwords_must_match': 'يجب أن تتطابق كلمات المرور',
  'password_reset_success': 'تمت إعادة ضبط كلمة المرور بنجاح!',
  'back_to_login': 'العودة إلى تسجيل الدخول',

  // Drawer Content
  'navigation': 'التنقل',
  'home': 'الرئيسية',
  'chat': 'الدردشة',
  'medical_records': 'السجلات الطبية',
  'lab_results': 'نتائج المختبر',
  'billing': 'الفواتير',
  'sign_up': 'التسجيل',
  'visit_website': 'زيارة الموقع الإلكتروني',
  'contact_us': 'اتصل بنا',
  'faq': 'الأسئلة الشائعة',
  'terms_conditions': 'الشروط والأحكام',
  'rate_app': 'تقييم التطبيق',
  'share_app': 'مشاركة التطبيق',
};
